### PR TITLE
fix(components/hook/usePortal): usePortal become SSR friendly

### LINKED ISSUE #2421: 🪲 hook/usePortal is not SSR friendly
### URL

https://sui-components.vercel.app/workbench/hook/usePortal/demo

### Steps to reproduce

use usePortal on a SSR site
it will broke cuz there is not document.body on first server render

### Expected Behavior

remove document.body from default arguments

### Screenshots

_No response_

### Which device have you used?

- [X] Desktop
- [X] Tablet
- [X] Mobile
- [X] smartTV

### Which operating systems have you used?

- [X] Windows
- [X] Linux
- [X] macOS

### browser and version

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by andresin87**
## hook/usePortal

`🔍 Show`

**TASK**: 
#2421 

### Types of changes

- [x] 🪲 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🧾 Documentation
- [ ] 📷 Demo
- [ ] 🧪 Test
- [ ] 🧠 Refactor
- [ ] 💄 Styles

### CODE REVIEW

File: components/hook/usePortal/src/index.js [hunk 1]
```diff
@@ -202,7 +202,7 @@ const usePortal = ({
             >
               {children}
             </As>,
-            target
+            target || document.body
```
Comment (andresin87) [inline components/hook/usePortal/src/index.js:205]: IMO this line will never be executed on server cuz `isReady`  L194 condition prevents that

Comment (oriolpuig) [reply components/hook/usePortal/src/index.js:205]: I'm not sure on `Portals`, but we use same approach when we have some `<Suspense>` on SSR's pages. So, let's go! 🚀
