### PR TITLE
fix(components/molecule/radioButtonGroup): props not being passed

### LINKED ISSUE #2447: 🪲 molecule/radioButtonGroup props not being passed
### URL

https://sui-components.vercel.app/workbench/molecule/radioButtonGroup/demo

### Steps to reproduce

_No response_

### Expected Behavior

_No response_

### Screenshots

_No response_

### Which device have you used?

- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] smartTV

### Which operating systems have you used?

- [ ] Windows
- [ ] Linux
- [ ] macOS

### browser and version

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by andresz1**
## molecule/radioButtonGroup

**TASK**: 

### Types of changes

- [X] 🪲 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🧾 Documentation
- [ ] 📷 Demo
- [ ] 🧪 Test
- [ ] 🧠 Refactor
- [ ] 💄 Styles

### Description, Motivation and Context
This PR fixes a bug where props were not propagated to radio buttons

### CODE REVIEW

**Review by andresin87 — APPROVED** [review]

File: components/molecule/radioButtonGroup/src/index.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ const MoleculeRadioButtonGroup = ({
               checked: ownProps.value === innerValue,
               onChange: handleChangeGroup,
               name,
-              props
+              ...props
```
Comment (jordevo) [inline components/molecule/radioButtonGroup/src/index.js:30]: 😨
