### PR TITLE
fix: autosuggest manage is opened state

### LINKED ISSUE #2079: Molecule/Autosuggest aria-expanded true when dropdown closed
**Describe the bug**
Molecule/Autosuggest: the area-expanded tag is showing true even though the dropdown is closed.

**Steps to reproduce**
Go to the console of the browser and write in the input, then delete everything. Open developer tools and look in elements. Find the sui-MoleculeAutosuggest (as per its class, it's a div) and check the area-expanded attribute.

It should show true only when: the grouping element this element owns or controls is expanded. (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded)

**Expected behavior**
To have the area-expanded as false when the drowndown is closed.

**Screenshots**

area-extended

**Environment / Context**
- Desktop
- iOS
- chrome 99

**Additional info**
-

### PR DESCRIPTION
**Pull request by Pato2790**
## Molecule/Autosuggest

`❓ Ask` 

**TASK**: #2079 

### Types of changes

- [X] 🪲 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🧾 Documentation
- [ ] 📷 Demo
- [ ] 🧪 Test
- [ ] 🧠 Refactor
- [ ] 💄 Styles

### Description, Motivation and Context

isOpen became controlled when autoClose props is false forced

### CODE REVIEW

File: components/molecule/autosuggest/src/components/SingleSelection/index.js [hunk 1]
```diff
@@ -18,7 +17,7 @@ const MoleculeAutosuggestSingleSelection = ({
   id,
   innerRefInput: refInput = {},
   inputMode,
-  isOpen,
```
Comment (andresin87) [inline components/molecule/autosuggest/src/components/SingleSelection/index.js]: is Must be kept as `isOpen`

File: components/molecule/autosuggest/src/components/SingleSelection/index.js [hunk 2]
```diff
@@ -91,11 +90,11 @@ const MoleculeAutosuggestSingleSelection = ({
       >
         <AtomInput />
       </InputWithClearUI>
-      {value && (
+      {(value || isOpenState) && (
```
Comment (andresin87) [inline components/molecule/autosuggest/src/components/SingleSelection/index.js]:
```suggestion
      {(value || isOpen) && (
```

File: components/molecule/autosuggest/src/components/SingleSelection/index.js [hunk 3]
```diff
@@ -91,11 +90,11 @@ const MoleculeAutosuggestSingleSelection = ({
...
         <MoleculeDropdownList
           size={size}
-          visible={isOpen && Children.count(children) > 0}
           onSelect={handleSelection}
+          visible={isOpenState && Children.count(children) > 0}
```
Comment (andresin87) [inline components/molecule/autosuggest/src/components/SingleSelection/index.js]:
```suggestion
          visible={isOpen && Children.count(children) > 0}
```

File: components/molecule/autosuggest/src/index.js [hunk 4]
```diff
@@ -188,7 +186,7 @@ const MoleculeAutosuggest = ({
     errorState,
     id,
     innerRefInput: refMoleculeAutosuggestInput,
-    isOpen: isOpenState,
+    isOpenState,
```
Comment (andresin87) [inline components/molecule/autosuggest/src/index.js]:
```suggestion
    isOpen: isOpenState,
```

File: components/molecule/autosuggest/src/components/SingleSelection/index.js [hunk 5]
```diff
@@ -18,7 +17,7 @@ const MoleculeAutosuggestSingleSelection = ({
   id,
   innerRefInput: refInput = {},
   inputMode,
-  isOpen,
+  isOpenState,
```
Comment (andresin87) [inline components/molecule/autosuggest/src/components/SingleSelection/index.js]:
```suggestion
  isOpen,
```

**Review by andresin87 — CHANGES_REQUESTED** [review]
.

**Review by andresin87 — APPROVED** [review]
